#include "VehicleComponentType.hpp"

namespace godot {
    void VehicleComponentType::_bind_methods() {
        BIND_ENUM_CONSTANT(COMPONENT_NONE);
        BIND_ENUM_CONSTANT(COMPONENT_GENERIC);
        BIND_ENUM_CONSTANT(COMPONENT_ENGINE);
        BIND_ENUM_CONSTANT(COMPONENT_HEATING);
        BIND_ENUM_CONSTANT(COMPONENT_LIGHTING);
        BIND_ENUM_CONSTANT(COMPONENT_LOAD);
        BIND_ENUM_CONSTANT(COMPONENT_DOORS);
        BIND_ENUM_CONSTANT(COMPONENT_HORNS);
        BIND_ENUM_CONSTANT(COMPONENT_WIPERS);
        BIND_ENUM_CONSTANT(COMPONENT_RADIO);
        BIND_ENUM_CONSTANT(COMPONENT_WHEELS);
        BIND_ENUM_CONSTANT(COMPONENT_TYPE_MAX);
    }
} // namespace godot
