#include "LibMaszynaUnits.hpp"

namespace godot {
    void LibMaszynaUnits::_bind_methods() {
        BIND_CONSTANT(SECONDS_PER_MINUTE);
        BIND_CONSTANT(MINUTES_PER_HOUR);
        BIND_CONSTANT(SECONDS_PER_HOUR);
        BIND_CONSTANT(MINUTES_PER_DAY);
        BIND_CONSTANT(HOURS_PER_DAY);
        BIND_CONSTANT(SECONDS_PER_DAY);
        BIND_CONSTANT(ARCSECONDS_PER_DEGREE);
        BIND_CONSTANT(USEC_PER_MSEC);
        BIND_CONSTANT(USEC_PER_SECOND);
        BIND_CONSTANT(METRES_PER_KILOMETRE);
        BIND_CONSTANT(NEWTONS_PER_KILONEWTON);
        BIND_CONSTANT(KILOGRAMS_PER_TONNE);
        BIND_CONSTANT(KILOPASCALS_PER_BAR);
        BIND_CONSTANT(JOULES_PER_KILOWATT_HOUR);
        BIND_CONSTANT(BYTES_PER_KILOBYTE);
    }
} // namespace godot
