#include "RailVehicleComponentType.hpp"

namespace godot {
    void RailVehicleComponentType::_bind_methods() {
        BIND_ENUM_CONSTANT(COMPONENT_BRAKES);
        BIND_ENUM_CONSTANT(COMPONENT_SPRING_BRAKE);
        BIND_ENUM_CONSTANT(COMPONENT_EP_ED_BRAKE);
        BIND_ENUM_CONSTANT(COMPONENT_BUFFERS);
        BIND_ENUM_CONSTANT(COMPONENT_SPEED_CONTROL);
        BIND_ENUM_CONSTANT(COMPONENT_SWITCHES);
        BIND_ENUM_CONSTANT(COMPONENT_AI_HINTS);
        BIND_ENUM_CONSTANT(COMPONENT_SECURITY);
        BIND_ENUM_CONSTANT(COMPONENT_UNIVERSAL_CONTROLLER);
        BIND_ENUM_CONSTANT(COMPONENT_MASTER_CONTROLLER);
        BIND_ENUM_CONSTANT(COMPONENT_POWER_SUPPLY);
        BIND_ENUM_CONSTANT(COMPONENT_ENGINE_POWER_SOURCE);
    }
} // namespace godot
