class_name MmdCabControlCaptions

## What a cab control is called, by its MMD label - the original's locale::label_cab_control()
## (translation.cpp:170-352), shown on hover. Captions are the original's English msgids, which the
## tooltip's Label translates from the game's own catalogue (MaszynaTranslationServer). A label not
## listed has no caption.
##
## The original's "brakeopmode_sw" and "doormode_sw" entries miss the trailing colon and never
## match; here they do.

const CAPTIONS:Dictionary[StringName, String] = {
    &"mainctrl": "master controller",
    &"jointctrl": "master controller",
    &"scndctrl": "second controller",
    &"shuntmodepower": "shunt mode power",
    &"tempomat_sw": "cruise control",
    &"tempomatoff_sw": "cruise control",
    &"speedinc_bt": "cruise control (speed)",
    &"speeddec_bt": "cruise control (speed)",
    &"speedctrlpowerinc_bt": "cruise control (power)",
    &"speedctrlpowerdec_bt": "cruise control (power)",
    &"speedbutton0": "cruise control (speed)",
    &"speedbutton1": "cruise control (speed)",
    &"speedbutton2": "cruise control (speed)",
    &"speedbutton3": "cruise control (speed)",
    &"speedbutton4": "cruise control (speed)",
    &"speedbutton5": "cruise control (speed)",
    &"speedbutton6": "cruise control (speed)",
    &"speedbutton7": "cruise control (speed)",
    &"speedbutton8": "cruise control (speed)",
    &"speedbutton9": "cruise control (speed)",
    &"distancecounter_sw": "distance counter",
    &"dirkey": "reverser",
    &"dirbackward_bt": "reverser",
    &"dirforward_bt": "reverser",
    &"dirneutral_bt": "reverser",
    &"brakectrl": "train brake",
    &"localbrake": "independent brake",
    &"manualbrake": "manual brake",
    &"alarmchain": "emergency brake",
    &"brakeprofile_sw": "brake acting speed",
    &"brakeprofileg_sw": "brake acting speed: cargo",
    &"brakeprofiler_sw": "brake acting speed: rapid",
    &"brakeopmode_sw": "brake operation mode",
    &"maxcurrent_sw": "motor overload relay threshold",
    &"waterpump_sw": "water pump",
    &"waterpumpbreaker_sw": "water pump breaker",
    &"waterheater_sw": "water heater",
    &"waterheaterbreaker_sw": "water heater breaker",
    &"watercircuitslink_sw": "water circuits link",
    &"fuelpump_sw": "fuel pump",
    &"oilpump_sw": "oil pump",
    &"motorblowersfront_sw": "motor blowers A",
    &"motorblowersrear_sw": "motor blowers B",
    &"motorblowersalloff_sw": "all motor blowers",
    &"coolingfans_sw": "cooling fans",
    &"main_off_bt": "line breaker",
    &"main_on_bt": "line breaker",
    &"security_reset_bt": "alerter",
    &"shp_reset_bt": "shp",
    &"releaser_bt": "independent brake releaser",
    &"sand_bt": "sandbox",
    &"antislip_bt": "wheelspin brake",
    &"horn_bt": "horn",
    &"hornlow_bt": "low tone horn",
    &"hornhigh_bt": "high tone horn",
    &"whistle_bt": "whistle",
    &"fuse_bt": "motor overload relay reset",
    &"converterfuse_bt": "converter overload relay reset",
    &"stlinoff_bt": "motor connectors",
    &"doorleftpermit_sw": "left door (permit)",
    &"doorrightpermit_sw": "right door (permit)",
    &"doorpermitpreset_sw": "door (permit)",
    &"door_left_sw": "left door",
    &"door_right_sw": "right door",
    &"doorlefton_sw": "left door (open)",
    &"doorrighton_sw": "right door (open)",
    &"doorleftoff_sw": "left door (close)",
    &"doorrightoff_sw": "right door (close)",
    &"doorallon_sw": "all doors (open)",
    &"dooralloff_sw": "all doors (close)",
    &"doorstep_sw": "doorstep",
    &"doormode_sw": "door control mode",
    &"departure_signal_bt": "departure signal",
    &"upperlight_sw": "upper headlight",
    &"leftlight_sw": "left headlight",
    &"rightlight_sw": "right headlight",
    &"dimheadlights_sw": "headlights dimmer",
    &"moderndimmer_sw": "headlights dimmer",
    &"leftend_sw": "left marker light",
    &"rightend_sw": "right marker light",
    &"lights_sw": "light pattern",
    &"rearupperlight_sw": "rear upper headlight",
    &"rearleftlight_sw": "rear left headlight",
    &"rearrightlight_sw": "rear right headlight",
    &"rearleftend_sw": "rear left marker light",
    &"rearrightend_sw": "rear right marker light",
    &"compressor_sw": "compressor",
    &"compressorlocal_sw": "local compressor",
    &"converter_sw": "converter",
    &"converterlocal_sw": "local converter",
    &"converteroff_sw": "converter",
    &"main_sw": "line breaker",
    &"radio_sw": "radio",
    &"radiochannel_sw": "radio channel",
    &"radiochannelprev_sw": "radio channel",
    &"radiochannelnext_sw": "radio channel",
    &"radiotest_sw": "radiostop test",
    &"radiostop_sw": "radiostop",
    &"radiocall3_sw": "radio call 3",
    &"radiovolume_sw": "radio volume",
    &"radiovolumenext_sw": "radio volume",
    &"radiovolumeprev_sw": "radio volume",
    &"pantfront_sw": "pantograph A",
    &"pantrear_sw": "pantograph B",
    &"pantfrontoff_sw": "pantograph A",
    &"pantrearoff_sw": "pantograph B",
    &"pantalloff_sw": "all pantographs",
    &"pantselected_sw": "selected pantograph",
    &"pantselectedoff_sw": "selected pantograph",
    &"pantselect_sw": "selected pantograph",
    &"pantvalves_sw": "selected pantograph",
    &"pantvalvesoff_bt": "all pantographs down",
    &"pantvalvesupdate_bt": "selected pantographs up",
    &"pantcompressor_sw": "pantograph compressor",
    &"pantcompressorvalve_sw": "pantograph 3 way valve",
    &"trainheating_sw": "heating",
    &"signalling_sw": "braking indicator",
    &"door_signalling_sw": "door locking",
    &"nextcurrent_sw": "current indicator source",
    &"instrumentlight_sw": "instrument light",
    &"dashboardlight_sw": "dashboard light",
    &"timetablelight_sw": "timetable light",
    &"cablight_sw": "interior light",
    &"cablightdim_sw": "interior light dimmer",
    &"compartmentlights_sw": "compartment lights",
    &"compartmentlightsoff_sw": "compartment lights",
    &"compartmentlightson_sw": "compartment lights",
    &"couplingdisconnect_sw": "coupling",
    &"battery_sw": "battery",
    &"batteryon_sw": "battery",
    &"batteryoff_sw": "battery",
    &"epbrake_bt": "ep brake",
    &"relayreset1_bt": "relay reset",
    &"relayreset2_bt": "relay reset",
    &"relayreset3_bt": "relay reset",
    &"springbrakeoff_bt": "spring brake",
    &"springbrakeon_bt": "spring brake",
    &"springbraketoggle_bt": "spring brake",
    &"universalbrake1_bt": "train brake",
    &"universalbrake2_bt": "train brake",
    &"universalbrake3_bt": "train brake",
    &"wipers_sw": "wipers mode selector",
    # not in the original's list, which leaves them without a tooltip; captioned here, with the
    # wrapper's own translations (addons/libmaszyna/translations)
    &"cabactivation_sw": "cab activation",
    &"mirrors_sw": "mirrors",
    &"radiocall1_sw": "radio call 1",
}


## universal0..29 (translation.cpp:316-345) - the original captions them all alike; here each
## carries its number, so the parts of one cab can be told apart
const UNIVERSAL_PREFIX:String = "universal"
const UNIVERSAL_CAPTION:String = "interactive part"


static func caption(label:StringName) -> String:
    var number:String = String(label).trim_prefix(UNIVERSAL_PREFIX)
    if String(label).begins_with(UNIVERSAL_PREFIX) and number.is_valid_int():
        # translated here: the tooltip's Label would not find the msgid with the number after it
        return "%s %s" % [TranslationServer.translate(UNIVERSAL_CAPTION), number]
    return CAPTIONS.get(label, "")
